name: Python

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          python-version: "3.11"

      - name: Run linter
        run: make lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run testing
        env:
          BASE_RPC_URL: ${{ secrets.BASE_RPC_URL }}
          BASE_SEPOLIA_RPC_URL: ${{ secrets.BASE_SEPOLIA_RPC_URL }}
          ETH_RPC_URL: ${{ secrets.ETH_RPC_URL }}
          ETH_SEPOLIA_RPC_URL: ${{ secrets.ETH_SEPOLIA_RPC_URL }}
          SOLANA_RPC_URL: ${{ secrets.SOLANA_RPC_URL }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          COOKIE_FUN_API_KEY: ${{ secrets.COOKIE_FUN_API_KEY }}
        run: make all-tests
